//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public string id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> privilege { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<int> age { get; set; }
        public string info { get; set; }
        public Nullable<System.DateTime> last_app { get; set; }
    }
}
